---
output:
  bookdown::pdf_document2: 
    keep_tex: true
    toc: false
---

```{r, include=FALSE}
library(emmeans)
library(here)
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.width = 8, fig.height = 7, full.fig.width = T, out.width="100%",dev=c("png") ) #, fig.pos = "H")
library(magrittr)
library(readr)
library(tidyverse)
library(fabricatr)
library(ggpmisc)
library(nlme)
library(broom.mixed)
library(ggResidpanel)
source("functions.R")
library(ggResidpanel)
library(boot) # for glm.diag.plots
library(tinytex)
```


## Appendix C: Model diagnosis {-}

### Population aboveground mass and stand density {-}

```{r, include=FALSE}
#### 2018 aboveground mass and density data #### 
amata18 <- read_csv("../2-Data/Clean/AMATA_18_clean.csv",
                    col_types = cols(Plot = col_factor(), 
                                     Block = col_factor(), 
                                     Crop = col_factor(),
                                     Crop_ID = col_factor(),
                                     Corn_weed_management = col_factor(),
                                     Year = col_character(),
                                     Male = col_integer(), 
                                     Female = col_integer()))



amata18$Crop_ID <- factor(amata18$Crop_ID, levels = c("C2", "S2",
                                                                "C3", "S3", "O3",
                                                                "C4", "S4", "O4", "A4"))

amata18 <- amata18 %<>%
  mutate_at(c("Block","Crop_ID","Rotation","Corn_weed_management"),
            funs(factor(.)))

#### 2019 aboveground mass and density data #### 

amata19 <- read_csv("../2-Data/Clean/AMATA_19_clean.csv",
                    col_types = cols(Plot = col_factor(), 
                                     Block = col_factor(), 
                                     Crop = col_factor(),
                                     Crop_ID = col_factor(),
                                     Corn_weed_management = col_factor(),
                                     Year = col_character(),
                                     Male = col_integer(), 
                                     Female = col_integer()))

amata19$Crop_ID <- factor(amata19$Crop_ID,
                          levels = c("C2", "S2",
                                     "C3", "S3", "O3",
                                     "C4", "S4", "O4", "A4"))

amata19 <- amata19 %<>%
  mutate_at(c("Block","Crop_ID","Corn_weed_management"),
            funs(factor(.)))

```



```{r pop-biom-18, echo=TRUE, fig.cap="Diagnosis plot for a model of the effects of crop identity and corn weed management on 2018 population aboveground mass."}
#### Did crop identity and corn weed management affect AMATA aboveground mass in 2018? ####

pop_biom18 <- lm(log(g_m_sq + 0.00025) ~ Block + Crop_ID*Corn_weed_management, 
                   data = amata18)
resid_panel(pop_biom18) 
```


```{r pop-biom-19, echo=TRUE, fig.cap="Diagnosis plot for a model of the effects of crop identity and corn weed management on 2019 population aboveground mass."}
#### Did crop identity and corn weed management affect AMATA aboveground mass in 2018? ####

pop_biom19<- lm(log(g_m_sq + 0.002) ~ Block + Crop_ID*Corn_weed_management,
                   data = amata19)

resid_panel(pop_biom19) 
```


```{r pop-dens-18, echo=TRUE,  fig.cap="Diagnosis plot for a model of the effects of crop identity and corn weed management on 2018 population density."}
#### Did crop identity and corn weed management affect AMATA density in 2018? ####

pop_dens18 <- lm(log(plant_m_sq + 0.025) ~ Block + Crop_ID*Corn_weed_management, 
                   data = amata18)

resid_panel(pop_dens18) 
```

```{r pop-dens-19, echo=TRUE,  fig.cap="Diagnosis plot for a model of the effects of crop identity and corn weed management on 2019 population density."}

#### Did crop identity and corn weed management affect AMATA density in 2019? ####
pop_dens19 <- lm(log(plant_m_sq + 0.025) ~ Block + Crop_ID*Corn_weed_management,
                   data = amata19)

resid_panel(pop_dens19) 

```



### Population sex ratio {-}



```{r sexr18, echo=TRUE, fig.cap="Diagnosis plot for a model of the effects of crop identity, corn weed management, and population aboveground mass on 2018 population sex ratio. Deviance = 165.91."}

#### Did crop identity and corn weed management had any effect on 2018 population sex ratio? ####
sexed18.glm <- glm(cbind(Female, Male) ~ Block + Crop_ID*Corn_weed_management,
  data=amata18, family=quasibinomial(link = "logit"))

glm.diag.plots(sexed18.glm) #in boot package

# deviance(sexed18.glm) # 165.9
```



```{r sexr18-biom, echo=TRUE, fig.cap="Diagnosis plot for a model of the effects of crop identity, corn weed management, and population aboveground mass on 2018 population sex ratio. Deviance = 104.26."}
#### Did population aboveground mass, crop identity and corn weed management had any effect on 2018 population sex ratio? ####

sexr18_biom_glm <- glm(cbind(Female, Male) ~ Block +  Crop_ID + Corn_weed_management + 
                          log(g_m_sq + 0.00025) +
                        Crop_ID:Corn_weed_management + 
                        log(g_m_sq + 0.00025):Crop_ID +
                        log(g_m_sq + 0.00025):Corn_weed_management +
                        log(g_m_sq + 0.00025):Crop_ID:Corn_weed_management ,
  data=amata18, family=quasibinomial(link = "logit"))

glm.diag.plots(sexr18_biom_glm)

#deviance(sexr18_biom_glm3) # 104.256
```



```{r sexr18-dens, echo=TRUE, fig.cap="Diagnosis plot for a model of the effects of crop identity, corn weed management, and population density on 2018 population sex ratio. Deviance = 82.12."}

#### Did crop identity, corn weed management and plant density affect AMATA aboveground mass in 2018? ####

sexr18_dens_glm3 <- glm(cbind(Female, Male) ~ Block  + Crop_ID + Corn_weed_management +
                          + log(plant_m_sq + 0.025)  +
                        Crop_ID:Corn_weed_management + 
                        log(plant_m_sq + 0.025):Crop_ID +
                        log(plant_m_sq + 0.025):Corn_weed_management +
                        log(plant_m_sq + 0.025):Crop_ID:Corn_weed_management ,
  data=amata18, family=quasibinomial(link = "logit"))

glm.diag.plots(sexr18_dens_glm3)

# GLM link function explained <http://web.pdx.edu/~newsomj/cdaclass/ho_glm.pdf>

# deviance(sexr18_dens_glm3 )  # = 82.12
```

### Individual female aboveground mass and fecundity {-}


```{r, include=FALSE}
## Read in the individual dried aboveground mass and fecundity 

fecundity18 <- read_csv(here("2 Data/Clean data/fecundity_18.csv"), 
    col_types = cols(Biomass = col_number(), 
        Seed = col_number()), na = "empty")

fecundity18$Crop_ID <- factor(fecundity18$Crop_ID, levels = c("C2", "S2",
                                                                "C3", "S3", "O3",
                                                                "C4", "S4", "O4", "A4"))

fecundity18$label <- paste(as.character(fecundity18$Rotation), "year", sep="-")

fecundity18  <- fecundity18   %<>%
  mutate_at(c("Block","Crop_ID", "Corn_weed_management", "bt"),funs(factor(.)))
```



```{r indiv-biom-18, echo=TRUE, fig.cap="Diagnosis plot for a model of crop identity and corn weed management effects on individual biomass."}

#### Did crop identity and corn weed management affect individual aboveground mass? ####
# Keep rows with no NAs only, fecundity18_b for Biomass

fecundity18_b <- fecundity18[complete.cases(fecundity18$Biomass), ]
# min(fecundity18_b$Biomass[fecundity18_b$Biomass > 0])

biomass.gls <- gls(log(Biomass + 0.005) ~ Block + Crop_ID + 
                     Corn_weed_management + Crop_ID:Corn_weed_management,
                   correlation=corCompSymm(form= ~1 | bt), #identifies each treatment within block
  data=fecundity18_b)

# Ho testing reference <http://web.pdx.edu/~newsomj/cdaclass/ho_glm.pdf>

diag_biom(biomass.gls, tag= "")
```



```{r indiv-seed-18, echo=TRUE, fig.cap="Diagnosis plot for a model of crop identity and corn weed management effect on individual fecundity."}

#### Did crop identity and corn weed management affect individual fecundity? {-} 

# Keep rows with no NAs only, fecundity18_s for Number of seeds
fecundity18_s <- fecundity18[complete.cases(fecundity18$Seed), ]

# min(fecundity18_s$Seed[fecundity18_s$Seed > 0])

seeds.gls <- gls(log(Seed + 1) ~ Block + Crop_ID + 
                   Corn_weed_management +
                   Crop_ID:Corn_weed_management,
                 correlation=corCompSymm(form= ~1 | bt), #identifies each treatment within block
  data=fecundity18_s)

diag_seed(seeds.gls , tag= "")
```




```{r indiv-biom-seed-18, echo = TRUE, fig.cap="Diagnosis plot for a model of crop identity and corn weed management effect on individual fecundity."}
### 18-mean full compound symmetry model
#### Did crop identity, corn weed management, and individual aboveground mass affect AMATA aboveground mass in 2018? #### 
fecundity18_sb <- fecundity18[complete.cases(fecundity18$Seed, fecundity18$Biomass), ]

#log(fecundity18_sb$Biomass )
allcrops.biom.seed.gls <- gls(log(Seed+1) ~ Block + log(Biomass + 0.005) + 
                                Crop_ID + Corn_weed_management +
                      Crop_ID:Corn_weed_management +
                      Crop_ID:log(Biomass + 0.005) + 
                        Corn_weed_management:log(Biomass + 0.005) +
                      Crop_ID:Corn_weed_management:log(Biomass + 0.005),
  correlation=corCompSymm(form= ~1 | bt), #identifies each treatment within block
  data=fecundity18_sb)

diag_seed(allcrops.biom.seed.gls, tag = "") 
```



