---
output:
  bookdown::pdf_document2: 
    keep_tex: true
    toc: false
    latex_engine: lualatex
    citation_package: natbib
bibliography: fecund.bib
csl: apa-no-ampersand.csl
---

Results of this study indicate that waterhemp was affected by crops and crop management in multiple ways, including a reduction in individual biomass and fecundity to the point of non-existence as occurred in 2019 soybean plots. 
Despite the 2018 and 2019 data being overdispersed, which resulted in high residual deviance, the significance of treatment effects was consistent. Crop identity was the most influential factor for all responses. Some covariation relationships were observed: population stand density affected sex ratio and female aboveground mass was a reliable predictor for fecundity.  

Waterhemp is a small-seeded species that is more sensitive to environmental stress than larger-seeded species [@harburLightGrowthRate2004]. In the present study, the number of stress and mortality factors likely increased as crop diversity increased temporally and spatially [@martinEffectCropRotation1993]. Stress and mortality factors arose from the strategic cropping system designs that employ crops of different phenology, management requirements, and relative competitiveness with weeds [@liebmanSustainableWeedManagement1990; @liebmanCropRotationIntercropping1993]. 

The two summer annual row crops in our study, corn and soybean, differed from the cool season and perennial crops, oat, red clover, and alfalfa with regard to the strongest selection pressure against weeds: herbicides. In corn (C2, C3, and C4), weeds were controlled with broadcast herbicide (conventional), or a combination of banded herbicide (38-cm strips on top of crop rows) and interrow cultivation. In soybean (S2, S3, and S4), weeds were controlled with broadcast herbicide as in conventional corn, with different active ingredients. In contrast, in the O3, O4, and A4 treatments, no herbicide or cultivation was applied, but those three crops were strategically introduced to the 3-year and 4-year rotations for their potential allelopathic and shading effects [@liebmanCropRotationIntercropping1993; @singhAllelopathicInteractionsAllelochemicals2003]. The spring establishment of O3 and O4 and overwintering of A4 treatments gave the crops a headstart for resource competition against waterhemp, a summer annual weed that emerged later [@hartzlerEffectCommonWaterhemp2004]. The timing of oat harvest in late July matched waterhemp's early reproductive stage [@buhlerRelativeEmergenceSequence2008; @horakGrowthAnalysisFour2000] and the resulting mechanical damage at this stage reduced the weed's reproductive potential. Intercropping oat and alfalfa can produce stronger weed suppression than might be achieved by each species grown as a sole crop [@laniniFightWeedsIncrease1992], whereas the effects of intercropping oat with red clover can be more variable [@samsonChoiceManagementCover1990]. For established alfalfa in the 4-year rotation, three to four hay cuts per crop season also served as a significant means of physical control and to reduce waterhemp reproductive potential.  


High waterhemp population stand densities in oat resulted from highly productive plants in the preceding corn and soybean phases of the rotation and signaled abundant replenishment of soil seedbanks. @dykeSuppressionCouchGrass1976 found that a clover and cereal intercrop substantially reduced weed emergence whereas @heggenstallerSeasonalPatternsPostdispersal2006 found that a triticale (*x Triticosecale* Wittmack) and red clover intercrop increased weed seedling recruitment. Taking these findings with the present study's observation that higher waterhemp population stand densities and lower waterhemp aboveground mass were found in small grain and forage crops than in row crops, it is possible that cold-tolerant crops can be used to stimulate and induce fatal germination to deplete the soil seedbank [@davisCroppingSystemEffects2003; @gallandtEffectCovercroppingSystems2005]. Eventually, as more mortality and stress factors are imposed on emerged weeds via various control methods, such as allelopathy and mechanical damage via crop harvest, those emerged plants might be expected to contribute fewer seeds to the soil seedbank. 

Waterhemp populations in three of the treatments, O3, O4, and A4, were slightly female-biased. Waterhemp populations in other treatments were even in sex ratio, which might be attributed to a more stressful conditions in small grain and forage crops than in row crops. A larger data set might help reducing the variance in sex ratio and provide a clearer understanding of the effect of corn weed management program on waterhemp sex ratio in subsequent oat and alfalfa phases. Systematic analysis is needed to identify the contribution of each stressor on waterhemp development and population dynamics. The 2019 sex ratio data were imputed without 2018 input but returned consistent conclusions on treatment effects, as compared to 2018. This consistency suggests an acceptable precision of the analysis model and the imputation algorithm. Since `pmm` seeks to fill in missing values with placeholders without changing the overall mean, it is reasonable to assume that the sex ratios in soybean eu's were even. The high herbicide efficacy in soybean was the strongest selection pressure on the exposed waterhemp populations.  



Our analysis indicated that female aboveground mass could be used to predict fecundity parsimoniously. The strong evidence of the significant interaction effect of weed management regime and crop identity on waterhemp fecundity justified the use of separate equations for each treatment. Since different sources of stress were introduced in the small grain and forages than in row crops, we attributed female-biasedness and lower fecundity in forages than in row crops to female herbaceous plants outperforming males under abiotic and biotic stresses [@juvanySexrelatedDifferencesStress2015]. The stand density and sex ratio data in this study does not provide sufficient information to establish a relationship between them, as was established between individual female biomass and fecundity. It would be helpful to explore the population stand density and sex ratio relationship with a bigger data set.  

In the present study, using mother plant reproduction potential (aboveground mass) gives a rough estimate of the number of seeds being added to the soil seedbank. Additionally, the total number of seeds produced at the end of the season in each treatment  depended on the parent plant density and population sex ratio. The possibility of post-harvest seed loss due to seed predators under different ground cover conditions adds to the complexity of seedbank dynamics. Red clover that remained after oat harvest and alfalfa living mulch may enhance granivore activities [@davisCroppingSystemEffects2003; @gallandtEffectCovercroppingSystems2005]. @heggenstallerSeasonalPatternsPostdispersal2006 found increased predation of velvetleaf (*Abutilon theophrasti* Medik) and giant foxtail (*Setaria faberi* Herrm) seeds in more diverse cropping systems than in shorter corn-soybean rotations. Overwintering crops such as alfalfa delayed pigweed (*Amaranthus quitensis* H.B.K.) emergence [@huarteUnderstandingMechanismsReduced2003] and can exude allelochemicals for weed suppression [@millerAllelopathyForageCrop1996]. Compared to the bare ground after corn and soybean production, the post-harvest environment in oat and alfalfa may induce more seed loss due to predation [@gallandtEffectCovercroppingSystems2005]. Waterhemp was not included in the @heggenstallerSeasonalPatternsPostdispersal2006 study, but waterhemp seeds are preferred over other species' seeds by field crickets and ground beetles [@vanderlaatPostdispersalWeedSeed2015] so it is likely that the small gran and forage crops in the present study enhanced waterhemp seed predation.   

More investigation is needed to determine how soil seedbank dynamics contribute to population dynamics in different scenarios, such as how female-biasedness could be potentially helpful to replenish a seedbank, whether sexual unevenness in a generation causes sexual unevenness in freshly produced seeds, and how those biases contribute to long-term population changes and competitiveness against crops. In the near-total control situation as occurred in the 2019 soybean plots, as the number of fresh seeds added to the soil seedbank can be considered negligible, other factors, such as sex ratio, population stand density, and plant size are of less practical concern. A more practical investigation would be to see how different levels of control efficacy translate into medium- and long-term population changes, because no herbicide is totally invulnerable to the evolution of resistance in weed populations. It would also be useful to see how populations would change once resistance occurred and how various control methods might contribute to resistance management.


 